Repository Figaarillo/greenbin-back, pull requests merged in 2024-07, with the labels that each got.

#1 fix: solucionar errores de configuracion de typeorm
  .env.dev
  src/shared/config/typeorm.config.ts
Labels: fix

#2 Feat/use case register new entity
  package.json
  src/entity/aplication/usecases/register.usecase.ts
  src/entity/domain/entities/entity.entity.ts
  src/entity/domain/errors/cannot-save-entity.error.ts
  src/entity/domain/errors/entity-schema-validation.error.ts
  src/entity/domain/payloads/entity.payload.ts
  src/entity/domain/repositories/entity.repository.ts
  src/entity/entity.bootstrap.ts
  src/entity/infrastructure/dtos/dto-types/dto-types.ts
  src/entity/infrastructure/dtos/register-entity.dto.ts
  src/entity/infrastructure/handler/entity.handler.ts
  src/entity/infrastructure/middlewares/zod-schema-validator.middleware.ts
  src/entity/infrastructure/repositories/typeorm/entity.typeorm.repository.ts
  src/entity/infrastructure/routes/entity.route.ts
  src/main.ts
  tsconfig.json
Labels: feature

#6 Refactor/migrate orm from typeorm to mikrorm
  package.json
  pnpm-lock.yaml
  src/app.ts
  src/db.ts
  src/entity/aplication/usecases/delete.usecase.ts
  src/entity/aplication/usecases/find-by-id.usecase.ts
  src/entity/aplication/usecases/find-by-name.usecase.ts
  src/entity/aplication/usecases/list.usecase.ts
  src/entity/aplication/usecases/register.usecase.ts
  src/entity/aplication/usecases/update.usecase.ts
  src/entity/domain/entities/entity.entity.ts
  src/entity/domain/repositories/entity.repository.ts
  src/entity/entity.bootstrap.ts
  src/entity/infrastructure/dtos/check-name.dto.ts
  src/entity/infrastructure/handler/entity.handler.ts
  src/entity/infrastructure/middlewares/zod-schema-validator.middleware.ts
  src/entity/infrastructure/repositories/mikro-orm/entity.mikroorm.repository.ts
  src/entity/infrastructure/repositories/typeorm/entity.typeorm.repository.ts
  src/entity/infrastructure/routes/entity.route.ts
  src/main.ts
  src/migrations/.snapshot-app_db.json
  src/migrations/Migration20240724233829.ts
  src/mikro-orm.config.ts
  src/shared/config/fastify.config.ts
  src/shared/config/server.config.ts
  src/shared/config/typeorm.config.ts
  src/shared/domain/entities/base.entity.ts
  src/shared/domain/exceptions/http-error-messages.exeption.ts
  src/shared/domain/exceptions/unexpected-error.ts
  src/shared/domain/types/primitives.ts
  src/user/aplication/usecases/delete.usecase.ts
  src/user/aplication/usecases/find-by-id.usecase.ts
  src/user/aplication/usecases/find-by-name.usecase.ts
  src/user/aplication/usecases/list.usecase.ts
  src/user/aplication/usecases/save.usecase.ts
  src/user/aplication/usecases/update.usecase.ts
  src/user/domain/entities/user.entity.ts
  src/user/domain/exceptions/http-error-messages.exeption.ts
  src/user/domain/exceptions/user-not-found.exception.ts
  src/user/domain/exceptions/user-schema-validation.error.ts
  src/user/domain/exceptions/value-object-format.exception.ts
  src/user/domain/payload/user.payload.ts
  src/user/domain/repository/user.repository.ts
  src/user/domain/value-objects/user.valueobject.ts
  src/user/infrastructure/dtos/dto-types/dto-types.ts
  src/user/infrastructure/dtos/id.dto.ts
  src/user/infrastructure/dtos/save-user.dto.ts
  src/user/infrastructure/dtos/update-user.dto.ts
  src/user/infrastructure/handler/user.handler.ts
  src/user/infrastructure/middlewares/zod-schema-validator.middleware.ts
  src/user/infrastructure/repositories/in-memory/user.in-memory.repository.ts
  src/user/infrastructure/repositories/typeorm/user.typeorm.repository.ts
  src/user/infrastructure/routes/user.route.ts
  src/user/user.bootstrap.ts
  temp/BaseEntity.js.json
  temp/BaseEntity.ts.json
  temp/EntityEntity.js.json
  temp/EntityEntity.ts.json
  tsconfig.json
Labels: refactor

#7 Feat/create crud for waste category
  src/app.ts
  src/migrations/.snapshot-app_db.json
  src/migrations/Migration20240726001845.ts
  src/waste-category/aplication/usecases/delete.usecase.ts
  src/waste-category/aplication/usecases/find-by-id.usecase.ts
  src/waste-category/aplication/usecases/list.usecase.ts
  src/waste-category/aplication/usecases/register.usecase.ts
  src/waste-category/aplication/usecases/update.usecase.ts
  src/waste-category/domain/entities/waste-category.entity.ts
  src/waste-category/domain/errors/cannot-save-category.error.ts
  src/waste-category/domain/errors/category-not-found.error.ts
  src/waste-category/domain/errors/category-schema-validation.error.ts
  src/waste-category/domain/payloads/waste-category.payload.ts
  src/waste-category/domain/repositories/waste-category.repository.ts
  src/waste-category/infrastructure/dtos/check-id.dto.ts
  src/waste-category/infrastructure/dtos/dto-types/dto-types.ts
  src/waste-category/infrastructure/dtos/register-waste-category.dto.ts
  src/waste-category/infrastructure/dtos/update-waste-category.dto.ts
  src/waste-category/infrastructure/handler/waste-category.handler.ts
  src/waste-category/infrastructure/middlewares/zod-schema-validator.middleware.ts
  src/waste-category/infrastructure/repositories/mikro-orm/waste-category.mikroorm.repository.ts
  src/waste-category/infrastructure/routes/waste-category.route.ts
  src/waste-category/waste-category.bootstrap.ts
  temp/WasteCategoryEntity.js.json
  temp/WasteCategoryEntity.ts.json
Labels: feature

#9 Feat/add cors config
  package.json
  pnpm-lock.yaml
  src/app.ts
  src/shared/config/fastify-cors.config.ts
Labels: feature

#8 Feat/create crud of responsible
  src/app.ts
  src/db.ts
  src/entity/infrastructure/repositories/mikro-orm/entity.mikroorm.repository.ts
  src/migrations/.snapshot-app_db.json
  src/migrations/Migration20240726220508.ts
  src/migrations/Migration20240726230213.ts
  src/migrations/Migration20240727173645.ts
  src/responsible/aplication/usecases/delete.usecase.ts
  src/responsible/aplication/usecases/find-by-id.usecase.ts
  src/responsible/aplication/usecases/list.usecase.ts
  src/responsible/aplication/usecases/register.usecase.ts
  src/responsible/aplication/usecases/update.usecase.ts
  src/responsible/domain/entities/responsible.entity.ts
  src/responsible/domain/errors/cannot-save-responsible.error.ts
  src/responsible/domain/errors/responsible-not-found.error.ts
  src/responsible/domain/errors/responsible-schema-validation.error.ts
  src/responsible/domain/payloads/responsible.payload.ts
  src/responsible/domain/payloads/responsible.update.payload.ts
  src/responsible/domain/repositories/responsible.repository.ts
  src/responsible/infrastructure/dtos/check-id.dto.ts
  src/responsible/infrastructure/dtos/dto-types/dto-types.ts
  src/responsible/infrastructure/dtos/register-responsible.dto.ts
  src/responsible/infrastructure/dtos/update-responsible.dto.ts
  src/responsible/infrastructure/handler/responsible.handler.ts
  src/responsible/infrastructure/middlewares/zod-schema-validator.middleware.ts
  src/responsible/infrastructure/repositories/mikro-orm/responsible.mikroorm.repository.ts
  src/responsible/infrastructure/routes/responsible.route.ts
  src/responsible/responsible.bootstrap.ts
  src/waste-category/aplication/usecases/find-by-id.usecase.ts
  temp/ResponsibleEntity.js.json
  temp/ResponsibleEntity.ts.json
Labels: feature
